using System;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator

namespace ESC2.Library.Data.Interfaces
{
    public interface IDataObject<T>
    {
        T Id { get; set; }
    }
}
