using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator

namespace ESC2.Library.Data.Interfaces
{
    public interface IDataProvider
    {
        DataTable GetData(string sql, List<DbQueryParameter> parameters = null, int timeout = 10);
        int Execute(string sql, List<DbQueryParameter> parameters = null, int timeout = 10);
    }
}
