using System;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator

namespace ESC2.Library.Data.Interfaces
{
    public interface IIdentityRepo<T> where T:IIdentityObject
    {
        long Save(T obj);
        T GetById(long id);
        void Delete(long id);
    }
}
