using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named AdjustmentSetRepo.cs
namespace ESC2.Module.System.Data.Repos.Operational
{
    public partial class AdjustmentSetRepo : AbstractDataRepo<ESC2.Module.System.Data.DataObjects.Operational.AdjustmentSet, Guid>
    {
        public AdjustmentSetRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "operational";
        public override string TableName => "adjustment_set";

        public override string InsertSql => @"
            INSERT INTO [operational].[adjustment_set] (
                [operational].[adjustment_set].[adjustment_set_id],
                [operational].[adjustment_set].[rule_id],
                [operational].[adjustment_set].[created_by_id],
                [operational].[adjustment_set].[created_on])
            VALUES ( 
                @Id,
                @RuleId,
                @CreatedById,
                @CreatedOn) ";

        public override string UpdateSql => @"
            UPDATE [operational].[adjustment_set] 
            SET [operational].[adjustment_set].[rule_id]=@RuleId,
                [operational].[adjustment_set].[created_by_id]=@CreatedById,
                [operational].[adjustment_set].[created_on]=@CreatedOn
            WHERE [operational].[adjustment_set].[adjustment_set_id]=@Id ";

        public override string SelectSql => @"
            SELECT [operational].[adjustment_set].[adjustment_set_id],
                   [operational].[adjustment_set].[rule_id],
                   [operational].[adjustment_set].[created_by_id],
                   [operational].[adjustment_set].[created_on]
            FROM [operational].[adjustment_set] ";

        public override ESC2.Module.System.Data.DataObjects.Operational.AdjustmentSet ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.Operational.AdjustmentSet();
            obj.Id = row.GetGuid("adjustment_set_id");
            obj.RuleId = row.GetGuid("rule_id");
            obj.CreatedById = row.GetGuid("created_by_id");
            obj.CreatedOn = row.GetDateTime("created_on");
            return obj;
        }

        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.Operational.AdjustmentSet obj)
        {
            List<DbQueryParameter> parameters = new List<DbQueryParameter>();
            parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("RuleId", obj.RuleId, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("CreatedById", obj.CreatedById, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("CreatedOn", obj.CreatedOn, DbQueryParameterType.DateTime));

            return parameters;
        }
    }
}
