using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named AuditRuleRepo.cs
namespace ESC2.Module.System.Data.Repos.Operational
{
    public partial class AuditRuleRepo : AbstractDataRepo<ESC2.Module.System.Data.DataObjects.Operational.AuditRule, Guid>
    {
        public AuditRuleRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "operational";
        public override string TableName => "audit_rule";

        public override string InsertSql => @"
            INSERT INTO [operational].[audit_rule] (
                [operational].[audit_rule].[audit_rule_id],
                [operational].[audit_rule].[comment],
                [operational].[audit_rule].[status],
                [operational].[audit_rule].[rule_id],
                [operational].[audit_rule].[evidence_set_id],
                [operational].[audit_rule].[audit_id],
                [operational].[audit_rule].[created_by_id],
                [operational].[audit_rule].[created_on],
                [operational].[audit_rule].[last_modified_by_id],
                [operational].[audit_rule].[last_modified_on])
            VALUES ( 
                @Id,
                @Comment,
                @Status,
                @RuleId,
                @EvidenceSetId,
                @AuditId,
                @CreatedById,
                @CreatedOn,
                @LastModifiedById,
                @LastModifiedOn) ";

        public override string UpdateSql => @"
            UPDATE [operational].[audit_rule] 
            SET [operational].[audit_rule].[comment]=@Comment,
                [operational].[audit_rule].[status]=@Status,
                [operational].[audit_rule].[rule_id]=@RuleId,
                [operational].[audit_rule].[evidence_set_id]=@EvidenceSetId,
                [operational].[audit_rule].[audit_id]=@AuditId,
                [operational].[audit_rule].[created_by_id]=@CreatedById,
                [operational].[audit_rule].[created_on]=@CreatedOn,
                [operational].[audit_rule].[last_modified_by_id]=@LastModifiedById,
                [operational].[audit_rule].[last_modified_on]=@LastModifiedOn
            WHERE [operational].[audit_rule].[audit_rule_id]=@Id ";

        public override string SelectSql => @"
            SELECT [operational].[audit_rule].[audit_rule_id],
                   [operational].[audit_rule].[comment],
                   [operational].[audit_rule].[status],
                   [operational].[audit_rule].[rule_id],
                   [operational].[audit_rule].[evidence_set_id],
                   [operational].[audit_rule].[audit_id],
                   [operational].[audit_rule].[created_by_id],
                   [operational].[audit_rule].[created_on],
                   [operational].[audit_rule].[last_modified_by_id],
                   [operational].[audit_rule].[last_modified_on]
            FROM [operational].[audit_rule] ";

        public override ESC2.Module.System.Data.DataObjects.Operational.AuditRule ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.Operational.AuditRule();
            obj.Id = row.GetGuid("audit_rule_id");
            obj.Comment = row.GetString("comment");
            obj.Status = row.GetString("status");
            obj.RuleId = row.GetGuid("rule_id");
            obj.EvidenceSetId = row.GetNullableGuid("evidence_set_id");
            obj.AuditId = row.GetGuid("audit_id");
            obj.CreatedById = row.GetGuid("created_by_id");
            obj.CreatedOn = row.GetDateTime("created_on");
            obj.LastModifiedById = row.GetGuid("last_modified_by_id");
            obj.LastModifiedOn = row.GetDateTime("last_modified_on");
            return obj;
        }

        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.Operational.AuditRule obj)
        {
            List<DbQueryParameter> parameters = new List<DbQueryParameter>();
            parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("Comment", obj.Comment, DbQueryParameterType.String));
            parameters.Add(new DbQueryParameter("Status", obj.Status, DbQueryParameterType.String));
            parameters.Add(new DbQueryParameter("RuleId", obj.RuleId, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("EvidenceSetId", obj.EvidenceSetId, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("AuditId", obj.AuditId, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("CreatedById", obj.CreatedById, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("CreatedOn", obj.CreatedOn, DbQueryParameterType.DateTime));
            parameters.Add(new DbQueryParameter("LastModifiedById", obj.LastModifiedById, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("LastModifiedOn", obj.LastModifiedOn, DbQueryParameterType.DateTime));

            return parameters;
        }
    }
}
