using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named AuditRepo.cs
namespace ESC2.Module.System.Data.Repos.Operational
{
    public partial class AuditRepo : AbstractDataRepo<ESC2.Module.System.Data.DataObjects.Operational.Audit, Guid>
    {
        public AuditRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "operational";
        public override string TableName => "audit";

        public override string InsertSql => @"
            INSERT INTO [operational].[audit] (
                [operational].[audit].[audit_id],
                [operational].[audit].[start_date],
                [operational].[audit].[end_date],
                [operational].[audit].[status],
                [operational].[audit].[summary],
                [operational].[audit].[assigned_user_id],
                [operational].[audit].[implementation_id],
                [operational].[audit].[created_by_id],
                [operational].[audit].[created_on],
                [operational].[audit].[last_modified_by_id],
                [operational].[audit].[last_modified_on])
            VALUES ( 
                @Id,
                @StartDate,
                @EndDate,
                @Status,
                @Summary,
                @AssignedUserId,
                @ImplementationId,
                @CreatedById,
                @CreatedOn,
                @LastModifiedById,
                @LastModifiedOn) ";

        public override string UpdateSql => @"
            UPDATE [operational].[audit] 
            SET [operational].[audit].[start_date]=@StartDate,
                [operational].[audit].[end_date]=@EndDate,
                [operational].[audit].[status]=@Status,
                [operational].[audit].[summary]=@Summary,
                [operational].[audit].[assigned_user_id]=@AssignedUserId,
                [operational].[audit].[implementation_id]=@ImplementationId,
                [operational].[audit].[created_by_id]=@CreatedById,
                [operational].[audit].[created_on]=@CreatedOn,
                [operational].[audit].[last_modified_by_id]=@LastModifiedById,
                [operational].[audit].[last_modified_on]=@LastModifiedOn
            WHERE [operational].[audit].[audit_id]=@Id ";

        public override string SelectSql => @"
            SELECT [operational].[audit].[audit_id],
                   [operational].[audit].[start_date],
                   [operational].[audit].[end_date],
                   [operational].[audit].[status],
                   [operational].[audit].[summary],
                   [operational].[audit].[assigned_user_id],
                   [operational].[audit].[implementation_id],
                   [operational].[audit].[created_by_id],
                   [operational].[audit].[created_on],
                   [operational].[audit].[last_modified_by_id],
                   [operational].[audit].[last_modified_on]
            FROM [operational].[audit] ";

        public override ESC2.Module.System.Data.DataObjects.Operational.Audit ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.Operational.Audit();
            obj.Id = row.GetGuid("audit_id");
            obj.StartDate = row.GetNullableDateTime("start_date");
            obj.EndDate = row.GetNullableDateTime("end_date");
            obj.Status = row.GetString("status");
            obj.Summary = row.GetString("summary");
            obj.AssignedUserId = row.GetNullableGuid("assigned_user_id");
            obj.ImplementationId = row.GetGuid("implementation_id");
            obj.CreatedById = row.GetGuid("created_by_id");
            obj.CreatedOn = row.GetDateTime("created_on");
            obj.LastModifiedById = row.GetGuid("last_modified_by_id");
            obj.LastModifiedOn = row.GetDateTime("last_modified_on");
            return obj;
        }

        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.Operational.Audit obj)
        {
            List<DbQueryParameter> parameters = new List<DbQueryParameter>();
            parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("StartDate", obj.StartDate, DbQueryParameterType.DateTime));
            parameters.Add(new DbQueryParameter("EndDate", obj.EndDate, DbQueryParameterType.DateTime));
            parameters.Add(new DbQueryParameter("Status", obj.Status, DbQueryParameterType.String));
            parameters.Add(new DbQueryParameter("Summary", obj.Summary, DbQueryParameterType.String));
            parameters.Add(new DbQueryParameter("AssignedUserId", obj.AssignedUserId, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("ImplementationId", obj.ImplementationId, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("CreatedById", obj.CreatedById, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("CreatedOn", obj.CreatedOn, DbQueryParameterType.DateTime));
            parameters.Add(new DbQueryParameter("LastModifiedById", obj.LastModifiedById, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("LastModifiedOn", obj.LastModifiedOn, DbQueryParameterType.DateTime));

            return parameters;
        }
    }
}
