using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named EvidenceSetRepo.cs
namespace ESC2.Module.System.Data.Repos.Operational
{
    public partial class EvidenceSetRepo : AbstractDataRepo<ESC2.Module.System.Data.DataObjects.Operational.EvidenceSet, Guid>
    {
        public EvidenceSetRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "operational";
        public override string TableName => "evidence_set";

        public override string InsertSql => @"
            INSERT INTO [operational].[evidence_set] (
                [operational].[evidence_set].[evidence_set_id],
                [operational].[evidence_set].[type],
                [operational].[evidence_set].[created_by_id],
                [operational].[evidence_set].[created_on])
            VALUES ( 
                @Id,
                @Type,
                @CreatedById,
                @CreatedOn) ";

        public override string UpdateSql => @"
            UPDATE [operational].[evidence_set] 
            SET [operational].[evidence_set].[type]=@Type,
                [operational].[evidence_set].[created_by_id]=@CreatedById,
                [operational].[evidence_set].[created_on]=@CreatedOn
            WHERE [operational].[evidence_set].[evidence_set_id]=@Id ";

        public override string SelectSql => @"
            SELECT [operational].[evidence_set].[evidence_set_id],
                   [operational].[evidence_set].[type],
                   [operational].[evidence_set].[created_by_id],
                   [operational].[evidence_set].[created_on]
            FROM [operational].[evidence_set] ";

        public override ESC2.Module.System.Data.DataObjects.Operational.EvidenceSet ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.Operational.EvidenceSet();
            obj.Id = row.GetGuid("evidence_set_id");
            obj.Type = row.GetString("type");
            obj.CreatedById = row.GetGuid("created_by_id");
            obj.CreatedOn = row.GetDateTime("created_on");
            return obj;
        }

        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.Operational.EvidenceSet obj)
        {
            List<DbQueryParameter> parameters = new List<DbQueryParameter>();
            parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("Type", obj.Type, DbQueryParameterType.String));
            parameters.Add(new DbQueryParameter("CreatedById", obj.CreatedById, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("CreatedOn", obj.CreatedOn, DbQueryParameterType.DateTime));

            return parameters;
        }
    }
}
