using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named EvidenceRepo.cs
namespace ESC2.Module.System.Data.Repos.Operational
{
    public partial class EvidenceRepo : AbstractDataRepo<ESC2.Module.System.Data.DataObjects.Operational.Evidence, Guid>
    {
        public EvidenceRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "operational";
        public override string TableName => "evidence";

        public override string InsertSql => @"
            INSERT INTO [operational].[evidence] (
                [operational].[evidence].[evidence_id],
                [operational].[evidence].[data_location],
                [operational].[evidence].[mime_type],
                [operational].[evidence].[evidence_set_id],
                [operational].[evidence].[created_by_id],
                [operational].[evidence].[created_on])
            VALUES ( 
                @Id,
                @DataLocation,
                @MimeType,
                @EvidenceSetId,
                @CreatedById,
                @CreatedOn) ";

        public override string UpdateSql => @"
            UPDATE [operational].[evidence] 
            SET [operational].[evidence].[data_location]=@DataLocation,
                [operational].[evidence].[mime_type]=@MimeType,
                [operational].[evidence].[evidence_set_id]=@EvidenceSetId,
                [operational].[evidence].[created_by_id]=@CreatedById,
                [operational].[evidence].[created_on]=@CreatedOn
            WHERE [operational].[evidence].[evidence_id]=@Id ";

        public override string SelectSql => @"
            SELECT [operational].[evidence].[evidence_id],
                   [operational].[evidence].[data_location],
                   [operational].[evidence].[mime_type],
                   [operational].[evidence].[evidence_set_id],
                   [operational].[evidence].[created_by_id],
                   [operational].[evidence].[created_on]
            FROM [operational].[evidence] ";

        public override string DeleteSql => @"DELETE FROM [operational].[evidence] WHERE [operational].[evidence].[evidence_id] = @Id";

        public override string GetByIdSql => $@"{SelectSql} WHERE [operational].[evidence].[evidence_id = @Id";
        public override ESC2.Module.System.Data.DataObjects.Operational.Evidence ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.Operational.Evidence();
            obj.Id = row.GetGuid("evidence_id");
            obj.DataLocation = row.GetString("data_location");
            obj.MimeType = row.GetString("mime_type");
            obj.EvidenceSetId = row.GetGuid("evidence_set_id");
            obj.CreatedById = row.GetGuid("created_by_id");
            obj.CreatedOn = row.GetDateTime("created_on");
            return obj;
        }

        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.Operational.Evidence obj)
        {
            List<DbQueryParameter> parameters = new List<DbQueryParameter>();
            parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("DataLocation", obj.DataLocation, DbQueryParameterType.String));
            parameters.Add(new DbQueryParameter("MimeType", obj.MimeType, DbQueryParameterType.String));
            parameters.Add(new DbQueryParameter("EvidenceSetId", obj.EvidenceSetId, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("CreatedById", obj.CreatedById, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("CreatedOn", obj.CreatedOn, DbQueryParameterType.DateTime));

            return parameters;
        }
    }
}
