using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named AuditDetailRepo.cs
namespace ESC2.Module.System.Data.Repos
{
    public partial class AuditDetailRepo : AbstractGuidRepo<ESC2.Module.System.Data.DataObjects.AuditDetail>
    {
        public AuditDetailRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "dbo";
        public override string TableName => "audit_detail";

        public override string InsertSql => @"
            INSERT INTO [dbo].[audit_detail] (
                [dbo].[audit_detail].[AuditDetailId],
                [dbo].[audit_detail].[AuditId],
                [dbo].[audit_detail].[RuleId],
                [dbo].[audit_detail].[Status],
                [dbo].[audit_detail].[Comment])
            VALUES ( 
                @Id,
                @AuditId,
                @RuleId,
                @Status,
                @Comment) ";

        public override string UpdateSql => @"
            UPDATE [dbo].[audit_detail] 
            SET [dbo].[audit_detail].[audit_id]=@AuditId,
                [dbo].[audit_detail].[rule_id]=@RuleId,
                [dbo].[audit_detail].[status]=@Status,
                [dbo].[audit_detail].[comment]=@Comment
            WHERE [dbo].[audit_detail].[audit_detail_id]=@Id ";

        public override string SelectSql => @"
            SELECT [dbo].[audit_detail].[audit_detail_id],
                   [dbo].[audit_detail].[audit_id],
                   [dbo].[audit_detail].[rule_id],
                   [dbo].[audit_detail].[status],
                   [dbo].[audit_detail].[comment]
            FROM [dbo].[audit_detail] ";

        public override ESC2.Module.System.Data.DataObjects.AuditDetail ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.AuditDetail();
            obj.Id = row.GetGuid("audit_detail_id");
            obj.AuditId = row.GetGuid("audit_id");
            obj.RuleId = row.GetNullableGuid("rule_id");
            obj.Status = row.GetString("status");
            obj.Comment = row.GetString("comment");
            return obj;
        }

        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.AuditDetail obj)
        {
            List<DbQueryParameter> parameters = new List<DbQueryParameter>();
            parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("AuditId", obj.AuditId, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("RuleId", obj.RuleId, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("Status", obj.Status, DbQueryParameterType.String));
            parameters.Add(new DbQueryParameter("Comment", obj.Comment, DbQueryParameterType.String));

            return parameters;
        }
    }
}
