using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named PeriodRepo.cs
namespace ESC2.Module.System.Data.Repos
{
    public partial class PeriodRepo : AbstractIdentityRepo<ESC2.Module.System.Data.DataObjects.Period>
    {
        public PeriodRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "dbo";
        public override string TableName => "period";

        public override string InsertSql => @"
            INSERT INTO [dbo].[period] (
                [dbo].[period].[period_id],
                [dbo].[period].[year],
                [dbo].[period].[month],
                [dbo].[period].[day],
                [dbo].[period].[day_of_week])
            VALUES ( 
                @Id,
                @Year,
                @Month,
                @Day,
                @DayOfWeek) ";

        public override string UpdateSql => @"
            UPDATE [dbo].[period] 
            SET [dbo].[period].[year]=@Year,
                [dbo].[period].[month]=@Month,
                [dbo].[period].[day]=@Day,
                [dbo].[period].[day_of_week]=@DayOfWeek
            WHERE [dbo].[period].[period_id]=@Id ";

        public override string SelectSql => @"
            SELECT [dbo].[period].[period_id],
                   [dbo].[period].[year],
                   [dbo].[period].[month],
                   [dbo].[period].[day],
                   [dbo].[period].[day_of_week]
            FROM [dbo].[period] ";

        public override ESC2.Module.System.Data.DataObjects.Period ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.Period();
            obj.Id = row.GetLong("period_id");
            obj.Year = row.GetInt("year");
            obj.Month = row.GetInt("month");
            obj.Day = row.GetInt("day");
            obj.DayOfWeek = row.GetByte("day_of_week");
            return obj;
        }

        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.Period obj)
        {
            List<DbQueryParameter> parameters = new List<DbQueryParameter>();
            parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("Year", obj.Year, DbQueryParameterType.Int32));
            parameters.Add(new DbQueryParameter("Month", obj.Month, DbQueryParameterType.Int32));
            parameters.Add(new DbQueryParameter("Day", obj.Day, DbQueryParameterType.Int32));
            parameters.Add(new DbQueryParameter("DayOfWeek", obj.DayOfWeek, DbQueryParameterType.Byte));

            return parameters;
        }
    }
}
