using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named ResourceCostFactRepo.cs
namespace ESC2.Module.System.Data.Repos
{
    public partial class ResourceCostFactRepo : AbstractGuidRepo<ESC2.Module.System.Data.DataObjects.ResourceCostFact>
    {
        public ResourceCostFactRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "dbo";
        public override string TableName => "resource_cost_fact";

        public override string InsertSql => @"
            INSERT INTO [dbo].[resource_cost_fact] (
                [dbo].[resource_cost_fact].[resource_cost_fact_id],
                [dbo].[resource_cost_fact].[role_id],
                [dbo].[resource_cost_fact].[start_period_id],
                [dbo].[resource_cost_fact].[end_period_id],
                [dbo].[resource_cost_fact].[cost_per_hour])
            VALUES ( 
                @Id,
                @RoleId,
                @StartPeriodId,
                @EndPeriodId,
                @CostPerHour) ";

        public override string UpdateSql => @"
            UPDATE [dbo].[resource_cost_fact] 
            SET [dbo].[resource_cost_fact].[role_id]=@RoleId,
                [dbo].[resource_cost_fact].[start_period_id]=@StartPeriodId,
                [dbo].[resource_cost_fact].[end_period_id]=@EndPeriodId,
                [dbo].[resource_cost_fact].[cost_per_hour]=@CostPerHour
            WHERE [dbo].[resource_cost_fact].[resource_cost_fact_id]=@Id ";

        public override string SelectSql => @"
            SELECT [dbo].[resource_cost_fact].[resource_cost_fact_id],
                   [dbo].[resource_cost_fact].[role_id],
                   [dbo].[resource_cost_fact].[start_period_id],
                   [dbo].[resource_cost_fact].[end_period_id],
                   [dbo].[resource_cost_fact].[cost_per_hour]
            FROM [dbo].[resource_cost_fact] ";

        public override ESC2.Module.System.Data.DataObjects.ResourceCostFact ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.ResourceCostFact();
            obj.Id = row.GetGuid("resource_cost_fact_id");
            obj.RoleId = row.GetGuid("role_id");
            obj.StartPeriodId = row.GetLong("start_period_id");
            obj.EndPeriodId = row.GetLong("end_period_id");
            obj.CostPerHour = row.GetDouble("cost_per_hour");
            return obj;
        }

        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.ResourceCostFact obj)
        {
            List<DbQueryParameter> parameters = new List<DbQueryParameter>();
            parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("RoleId", obj.RoleId, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("StartPeriodId", obj.StartPeriodId, DbQueryParameterType.Int64));
            parameters.Add(new DbQueryParameter("EndPeriodId", obj.EndPeriodId, DbQueryParameterType.Int64));
            parameters.Add(new DbQueryParameter("CostPerHour", obj.CostPerHour, DbQueryParameterType.Double));

            return parameters;
        }
    }
}
