using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named RoleRepo.cs
namespace ESC2.Module.System.Data.Repos
{
    public partial class RoleRepo : AbstractGuidRepo<ESC2.Module.System.Data.DataObjects.Role>
    {
        public RoleRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "dbo";
        public override string TableName => "role";

        public override string InsertSql => @"
            INSERT INTO [dbo].[role] (
                [dbo].[role].[role_id],
                [dbo].[role].[name])
            VALUES ( 
                @Id,
                @Name) ";

        public override string UpdateSql => @"
            UPDATE [dbo].[role] 
            SET [dbo].[role].[name]=@Name
            WHERE [dbo].[role].[role_id]=@Id ";

        public override string SelectSql => @"
            SELECT [dbo].[role].[role_id],
                   [dbo].[role].[name]
            FROM [dbo].[role] ";

        public override ESC2.Module.System.Data.DataObjects.Role ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.Role();
            obj.Id = row.GetGuid("role_id");
            obj.Name = row.GetString("name");
            return obj;
        }

        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.Role obj)
        {
            List<DbQueryParameter> parameters = new List<DbQueryParameter>();
            parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("Name", obj.Name, DbQueryParameterType.String));

            return parameters;
        }
    }
}
