using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named AssetType.cs

namespace ESC2.Library.Data.DataObjects
{
    public partial class AssetType : IGuidObject
    {
        public AssetType()
        {
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public Guid? StigId { get; set; }
        public Guid AssetGroupId { get; set; }
    }
}
