using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named Employee.cs

namespace ESC2.Library.Data.DataObjects
{
    public partial class Employee : IGuidObject
    {
        public Employee()
        {
        }

        public Guid Id { get; set; }
        public string GivenName { get; set; }
        public string FamilyName { get; set; }
        public string Email { get; set; }
        public string JobTitle { get; set; }
        public Guid DepartmentId { get; set; }
    }
}
