using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named Evidence.cs

namespace ESC2.Library.Data.DataObjects
{
    public partial class Evidence : IGuidObject
    {
        public Evidence()
        {
        }

        public Guid Id { get; set; }
        public string DataLocation { get; set; }
        public string MimeType { get; set; }
        public Guid EvidenceSetId { get; set; }
    }
}
