using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named ImplementationRule.cs

namespace ESC2.Library.Data.DataObjects
{
    public partial class ImplementationRule : IGuidObject
    {
        public ImplementationRule()
        {
        }

        public Guid Id { get; set; }
        public Guid RuleId { get; set; }
        public Guid ImplementationId { get; set; }
        public string Status { get; set; }
        public string FindingDetails { get; set; }
        public string Comments { get; set; }
        public string SeverityOverride { get; set; }
        public string SeverityJustification { get; set; }
        public Guid? EvidenceSetId { get; set; }
    }
}
