using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named Rule.cs

namespace ESC2.Library.Data.DataObjects
{
    public partial class Rule : IGuidObject
    {
        public Rule()
        {
        }

        public Guid Id { get; set; }
        public Guid VersionId { get; set; }
        public string Number { get; set; }
        public string Severity { get; set; }
        public string Version { get; set; }
        public string Title { get; set; }
        public string Fix { get; set; }
        public string Check { get; set; }
        public string Cci { get; set; }
    }
}
