using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named User.cs

namespace ESC2.Library.Data.DataObjects
{
    public partial class User : IGuidObject
    {
        public User()
        {
        }

        public Guid Id { get; set; }
        public string Role { get; set; }
        public bool IsEnabled { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public Guid EmployeeId { get; set; }
    }
}
