using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named Version.cs

namespace ESC2.Library.Data.DataObjects
{
    public partial class Version : IGuidObject
    {
        public Version()
        {
            Id = Guid.NewGuid();
        }

        public Guid Id { get; set; }
        public Guid StigId { get; set; }
        public string Number { get; set; }
        public string Status { get; set; }
        public DateTime StatusDate { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Publisher { get; set; }
        public string Source { get; set; }
        public string Filename { get; set; }
    }
}
