using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named DayPeriodRepo.cs
namespace ESC2.Module.System.Data.Repos.Warehouse
{
    public partial class DayPeriodRepo : AbstractDataRepo<ESC2.Module.System.Data.DataObjects.Warehouse.DayPeriod, Int32>
    {
        public DayPeriodRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "warehouse";
        public override string TableName => "day_period";

        public override string InsertSql => @"
            INSERT INTO [warehouse].[day_period] (
                [warehouse].[day_period].[day_period_id],
                [warehouse].[day_period].[year],
                [warehouse].[day_period].[month],
                [warehouse].[day_period].[day],
                [warehouse].[day_period].[day_of_week])
            VALUES ( 
                @Id,
                @Year,
                @Month,
                @Day,
                @DayOfWeek) ";

        public override string UpdateSql => @"
            UPDATE [warehouse].[day_period] 
            SET [warehouse].[day_period].[year]=@Year,
                [warehouse].[day_period].[month]=@Month,
                [warehouse].[day_period].[day]=@Day,
                [warehouse].[day_period].[day_of_week]=@DayOfWeek
            WHERE [warehouse].[day_period].[day_period_id]=@Id ";

        public override string SelectSql => @"
            SELECT [warehouse].[day_period].[day_period_id],
                   [warehouse].[day_period].[year],
                   [warehouse].[day_period].[month],
                   [warehouse].[day_period].[day],
                   [warehouse].[day_period].[day_of_week]
            FROM [warehouse].[day_period] ";

        public override string DeleteSql => @"DELETE FROM [warehouse].[day_period] WHERE [warehouse].[day_period].[day_period_id] = @Id";

        public override string GetByIdSql => $@"{SelectSql} WHERE [warehouse].[day_period].[day_period_id = @Id";
        public override ESC2.Module.System.Data.DataObjects.Warehouse.DayPeriod ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.Warehouse.DayPeriod();
            obj.Id = row.GetInt("day_period_id");
            obj.Year = row.GetInt("year");
            obj.Month = row.GetInt("month");
            obj.Day = row.GetInt("day");
            obj.DayOfWeek = row.GetByte("day_of_week");
            return obj;
        }

        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.Warehouse.DayPeriod obj)
        {
            List<DbQueryParameter> parameters = new List<DbQueryParameter>();
            parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("Year", obj.Year, DbQueryParameterType.Int32));
            parameters.Add(new DbQueryParameter("Month", obj.Month, DbQueryParameterType.Int32));
            parameters.Add(new DbQueryParameter("Day", obj.Day, DbQueryParameterType.Int32));
            parameters.Add(new DbQueryParameter("DayOfWeek", obj.DayOfWeek, DbQueryParameterType.Byte));

            return parameters;
        }
    }
}
