using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named ImplementationFactRepo.cs
namespace ESC2.Module.System.Data.Repos.Warehouse
{
    public partial class ImplementationFactRepo : AbstractDataRepo<ESC2.Module.System.Data.DataObjects.Warehouse.ImplementationFact, Int32>
    {
        public ImplementationFactRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "warehouse";
        public override string TableName => "implementation_fact";

        public override string InsertSql => @"
            INSERT INTO [warehouse].[implementation_fact] (
                [warehouse].[implementation_fact].[implementation_id],
                [warehouse].[implementation_fact].[asset_id],
                [warehouse].[implementation_fact].[implementation_guide_id],
                [warehouse].[implementation_fact].[employee_id],
                [warehouse].[implementation_fact].[started_on_period_id],
                [warehouse].[implementation_fact].[completed_on_period_id],
                [warehouse].[implementation_fact].[hours_to_complete])
            VALUES ( 
                @ImplementationId,
                @AssetId,
                @ImplementationGuideId,
                @EmployeeId,
                @StartedOnPeriodId,
                @CompletedOnPeriodId,
                @HoursToComplete) ";

        public override string UpdateSql => @"
            UPDATE [warehouse].[implementation_fact] 
            SET [warehouse].[implementation_fact].[implementation_id]=@ImplementationId,
                [warehouse].[implementation_fact].[asset_id]=@AssetId,
                [warehouse].[implementation_fact].[implementation_guide_id]=@ImplementationGuideId,
                [warehouse].[implementation_fact].[employee_id]=@EmployeeId,
                [warehouse].[implementation_fact].[started_on_period_id]=@StartedOnPeriodId,
                [warehouse].[implementation_fact].[completed_on_period_id]=@CompletedOnPeriodId,
                [warehouse].[implementation_fact].[hours_to_complete]=@HoursToComplete
            WHERE [warehouse].[implementation_fact].[implementation_fact_id]=@Id ";

        public override string SelectSql => @"
            SELECT [warehouse].[implementation_fact].[implementation_fact_id],
                   [warehouse].[implementation_fact].[implementation_id],
                   [warehouse].[implementation_fact].[asset_id],
                   [warehouse].[implementation_fact].[implementation_guide_id],
                   [warehouse].[implementation_fact].[employee_id],
                   [warehouse].[implementation_fact].[started_on_period_id],
                   [warehouse].[implementation_fact].[completed_on_period_id],
                   [warehouse].[implementation_fact].[hours_to_complete]
            FROM [warehouse].[implementation_fact] ";

        public override ESC2.Module.System.Data.DataObjects.Warehouse.ImplementationFact ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.Warehouse.ImplementationFact();
            obj.Id = row.GetInt("implementation_fact_id");
            obj.ImplementationId = row.GetGuid("implementation_id");
            obj.AssetId = row.GetGuid("asset_id");
            obj.ImplementationGuideId = row.GetGuid("implementation_guide_id");
            obj.EmployeeId = row.GetGuid("employee_id");
            obj.StartedOnPeriodId = row.GetInt("started_on_period_id");
            obj.CompletedOnPeriodId = row.GetInt("completed_on_period_id");
            obj.HoursToComplete = row.GetDouble("hours_to_complete");
            return obj;
        }

        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.Warehouse.ImplementationFact obj)
        {
            List<DbQueryParameter> parameters = new List<DbQueryParameter>();
            parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("ImplementationId", obj.ImplementationId, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("AssetId", obj.AssetId, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("ImplementationGuideId", obj.ImplementationGuideId, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("EmployeeId", obj.EmployeeId, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("StartedOnPeriodId", obj.StartedOnPeriodId, DbQueryParameterType.Int32));
            parameters.Add(new DbQueryParameter("CompletedOnPeriodId", obj.CompletedOnPeriodId, DbQueryParameterType.Int32));
            parameters.Add(new DbQueryParameter("HoursToComplete", obj.HoursToComplete, DbQueryParameterType.Double));

            return parameters;
        }
    }
}
