using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named LogSeverityRepo.cs
namespace ESC2.Module.System.Data.Repos.Warehouse
{
    public partial class LogSeverityRepo : AbstractDataRepo<ESC2.Module.System.Data.DataObjects.Warehouse.LogSeverity, Byte>
    {
        public LogSeverityRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "warehouse";
        public override string TableName => "log_severity";

        public override string InsertSql => @"
            INSERT INTO [warehouse].[log_severity] (
                [warehouse].[log_severity].[log_severity_id],
                [warehouse].[log_severity].[name])
            VALUES ( 
                @Id,
                @Name) ";

        public override string UpdateSql => @"
            UPDATE [warehouse].[log_severity] 
            SET [warehouse].[log_severity].[name]=@Name
            WHERE [warehouse].[log_severity].[log_severity_id]=@Id ";

        public override string SelectSql => @"
            SELECT [warehouse].[log_severity].[log_severity_id],
                   [warehouse].[log_severity].[name]
            FROM [warehouse].[log_severity] ";

        public override ESC2.Module.System.Data.DataObjects.Warehouse.LogSeverity ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.Warehouse.LogSeverity();
            obj.Id = row.GetByte("log_severity_id");
            obj.Name = row.GetString("name");
            return obj;
        }

        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.Warehouse.LogSeverity obj)
        {
            List<DbQueryParameter> parameters = new List<DbQueryParameter>();
            parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("Name", obj.Name, DbQueryParameterType.String));

            return parameters;
        }
    }
}
