using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named ResourceCostFactRepo.cs
namespace ESC2.Module.System.Data.Repos.Warehouse
{
    public partial class ResourceCostFactRepo : AbstractDataRepo<ESC2.Module.System.Data.DataObjects.Warehouse.ResourceCostFact, Int32>
    {
        public ResourceCostFactRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "warehouse";
        public override string TableName => "resource_cost_fact";

        public override string InsertSql => @"
            INSERT INTO [warehouse].[resource_cost_fact] (
                [warehouse].[resource_cost_fact].[user_role_id],
                [warehouse].[resource_cost_fact].[start_period_id],
                [warehouse].[resource_cost_fact].[end_period_id],
                [warehouse].[resource_cost_fact].[cost_per_hour])
            VALUES ( 
                @UserRoleId,
                @StartPeriodId,
                @EndPeriodId,
                @CostPerHour) ";

        public override string UpdateSql => @"
            UPDATE [warehouse].[resource_cost_fact] 
            SET [warehouse].[resource_cost_fact].[user_role_id]=@UserRoleId,
                [warehouse].[resource_cost_fact].[start_period_id]=@StartPeriodId,
                [warehouse].[resource_cost_fact].[end_period_id]=@EndPeriodId,
                [warehouse].[resource_cost_fact].[cost_per_hour]=@CostPerHour
            WHERE [warehouse].[resource_cost_fact].[resource_cost_fact_id]=@Id ";

        public override string SelectSql => @"
            SELECT [warehouse].[resource_cost_fact].[resource_cost_fact_id],
                   [warehouse].[resource_cost_fact].[user_role_id],
                   [warehouse].[resource_cost_fact].[start_period_id],
                   [warehouse].[resource_cost_fact].[end_period_id],
                   [warehouse].[resource_cost_fact].[cost_per_hour]
            FROM [warehouse].[resource_cost_fact] ";

        public override string DeleteSql => @"DELETE FROM [warehouse].[resource_cost_fact] WHERE [warehouse].[resource_cost_fact].[resource_cost_fact_id] = @Id";

        public override string GetByIdSql => $@"{SelectSql} WHERE [warehouse].[resource_cost_fact].[resource_cost_fact_id = @Id";
        public override ESC2.Module.System.Data.DataObjects.Warehouse.ResourceCostFact ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.Warehouse.ResourceCostFact();
            obj.Id = row.GetInt("resource_cost_fact_id");
            obj.UserRoleId = row.GetGuid("user_role_id");
            obj.StartPeriodId = row.GetInt("start_period_id");
            obj.EndPeriodId = row.GetInt("end_period_id");
            obj.CostPerHour = row.GetDouble("cost_per_hour");
            return obj;
        }

        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.Warehouse.ResourceCostFact obj)
        {
            List<DbQueryParameter> parameters = new List<DbQueryParameter>();
            parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("UserRoleId", obj.UserRoleId, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("StartPeriodId", obj.StartPeriodId, DbQueryParameterType.Int32));
            parameters.Add(new DbQueryParameter("EndPeriodId", obj.EndPeriodId, DbQueryParameterType.Int32));
            parameters.Add(new DbQueryParameter("CostPerHour", obj.CostPerHour, DbQueryParameterType.Double));

            return parameters;
        }
    }
}
