using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.DataObjects;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named AssetGroupRepo.cs
namespace ESC2.Library.Data.Repos
{
    public partial class AssetGroupRepo : AbstractGuidRepo<ESC2.Library.Data.DataObjects.AssetGroup>
    {
        public AssetGroupRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "dbo";
        public override string TableName => "asset_group";

        public override string InsertSql => @"
            INSERT INTO [dbo].[asset_group] (
                [dbo].[asset_group].[AssetGroupId],
                [dbo].[asset_group].[Name])
            VALUES ( 
                @Id,
                @Name) ";

        public override string UpdateSql => @"
            UPDATE [dbo].[asset_group] 
            SET [dbo].[asset_group].[name]=@Name
            WHERE [dbo].[asset_group].[asset_group_id]=@Id ";

        public override string SelectSql => @"
            SELECT [dbo].[asset_group].[asset_group_id],
                   [dbo].[asset_group].[name]
            FROM [dbo].[asset_group] ";

        public override ESC2.Library.Data.DataObjects.AssetGroup ToObject(DataRow row)
        {
            var obj = new ESC2.Library.Data.DataObjects.AssetGroup();
            obj.Id = row.GetGuid("asset_group_id");
            obj.Name = row.GetString("name");
            return obj;
        }


        public override List<DbQueryParameter> ToParameters(ESC2.Library.Data.DataObjects.AssetGroup obj)
         {
             List<DbQueryParameter> parameters = new List<DbQueryParameter>();
             parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
             parameters.Add(new DbQueryParameter("Name", obj.Name, DbQueryParameterType.String));

             return parameters;
         }


    }
}
