using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.DataObjects;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named AssetRepo.cs
namespace ESC2.Library.Data.Repos
{
    public partial class AssetRepo : AbstractGuidRepo<ESC2.Library.Data.DataObjects.Asset>
    {
        public AssetRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "dbo";
        public override string TableName => "asset";

        public override string InsertSql => @"
            INSERT INTO [dbo].[asset] (
                [dbo].[asset].[AssetId],
                [dbo].[asset].[Name],
                [dbo].[asset].[Description],
                [dbo].[asset].[Status],
                [dbo].[asset].[ContactEmployeeId],
                [dbo].[asset].[OwningDepartmentId],
                [dbo].[asset].[ParentAssetId],
                [dbo].[asset].[AssetTypeId],
                [dbo].[asset].[PurchaseDate],
                [dbo].[asset].[InServiceDate],
                [dbo].[asset].[RetiredDate])
            VALUES ( 
                @Id,
                @Name,
                @Description,
                @Status,
                @ContactEmployeeId,
                @OwningDepartmentId,
                @ParentAssetId,
                @AssetTypeId,
                @PurchaseDate,
                @InServiceDate,
                @RetiredDate) ";

        public override string UpdateSql => @"
            UPDATE [dbo].[asset] 
            SET [dbo].[asset].[name]=@Name,
                [dbo].[asset].[description]=@Description,
                [dbo].[asset].[status]=@Status,
                [dbo].[asset].[contact_employee_id]=@ContactEmployeeId,
                [dbo].[asset].[owning_department_id]=@OwningDepartmentId,
                [dbo].[asset].[parent_asset_id]=@ParentAssetId,
                [dbo].[asset].[asset_type_id]=@AssetTypeId,
                [dbo].[asset].[purchase_date]=@PurchaseDate,
                [dbo].[asset].[in_service_date]=@InServiceDate,
                [dbo].[asset].[retired_date]=@RetiredDate
            WHERE [dbo].[asset].[asset_id]=@Id ";

        public override string SelectSql => @"
            SELECT [dbo].[asset].[asset_id],
                   [dbo].[asset].[name],
                   [dbo].[asset].[description],
                   [dbo].[asset].[status],
                   [dbo].[asset].[contact_employee_id],
                   [dbo].[asset].[owning_department_id],
                   [dbo].[asset].[parent_asset_id],
                   [dbo].[asset].[asset_type_id],
                   [dbo].[asset].[purchase_date],
                   [dbo].[asset].[in_service_date],
                   [dbo].[asset].[retired_date]
            FROM [dbo].[asset] ";

        public override ESC2.Library.Data.DataObjects.Asset ToObject(DataRow row)
        {
            var obj = new ESC2.Library.Data.DataObjects.Asset();
            obj.Id = row.GetGuid("asset_id");
            obj.Name = row.GetString("name");
            obj.Description = row.GetString("description");
            obj.Status = row.GetString("status");
            obj.ContactEmployeeId = row.GetNullableGuid("contact_employee_id");
            obj.OwningDepartmentId = row.GetNullableGuid("owning_department_id");
            obj.ParentAssetId = row.GetNullableGuid("parent_asset_id");
            obj.AssetTypeId = row.GetGuid("asset_type_id");
            obj.PurchaseDate = row.GetNullableDateTime("purchase_date");
            obj.InServiceDate = row.GetNullableDateTime("in_service_date");
            obj.RetiredDate = row.GetNullableDateTime("retired_date");
            return obj;
        }


        public override List<DbQueryParameter> ToParameters(ESC2.Library.Data.DataObjects.Asset obj)
         {
             List<DbQueryParameter> parameters = new List<DbQueryParameter>();
             parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
             parameters.Add(new DbQueryParameter("Name", obj.Name, DbQueryParameterType.String));
             parameters.Add(new DbQueryParameter("Description", obj.Description, DbQueryParameterType.String));
             parameters.Add(new DbQueryParameter("Status", obj.Status, DbQueryParameterType.String));
             parameters.Add(new DbQueryParameter("ContactEmployeeId", obj.ContactEmployeeId, DbQueryParameterType.Guid));
             parameters.Add(new DbQueryParameter("OwningDepartmentId", obj.OwningDepartmentId, DbQueryParameterType.Guid));
             parameters.Add(new DbQueryParameter("ParentAssetId", obj.ParentAssetId, DbQueryParameterType.Guid));
             parameters.Add(new DbQueryParameter("AssetTypeId", obj.AssetTypeId, DbQueryParameterType.Guid));
             parameters.Add(new DbQueryParameter("PurchaseDate", obj.PurchaseDate, DbQueryParameterType.DateTime));
             parameters.Add(new DbQueryParameter("InServiceDate", obj.InServiceDate, DbQueryParameterType.DateTime));
             parameters.Add(new DbQueryParameter("RetiredDate", obj.RetiredDate, DbQueryParameterType.DateTime));

             return parameters;
         }


    }
}
