using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named AuditFact.cs

namespace ESC2.Module.System.Data.DataObjects.Warehouse
{
    public partial class AuditFact : IDataObject<int>
    {
        public AuditFact()
        {
            Id = -1;
        }

        public int Id { get; set; }
        public Guid AuditId { get; set; }
        public Guid AssetId { get; set; }
        public Guid ImplementationGuideId { get; set; }
        public Guid EmployeeId { get; set; }
        public int StartedOnPeriodId { get; set; }
        public int CompletedOnPeriodId { get; set; }
        public double HoursToComplete { get; set; }
    }
}
