using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named LogDailyFact.cs

namespace ESC2.Module.System.Data.DataObjects.Warehouse
{
    public partial class LogDailyFact : IDataObject<long>
    {
        public LogDailyFact()
        {
            Id = -1;
        }

        public long Id { get; set; }
        public Guid AssetId { get; set; }
        public int DayPeriodId { get; set; }
        public byte LogSeverityId { get; set; }
        public short LogSourceId { get; set; }
        public long Count { get; set; }
    }
}
