using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named ResourceCostFact.cs

namespace ESC2.Module.System.Data.DataObjects.Warehouse
{
    public partial class ResourceCostFact : IDataObject<int>
    {
        public ResourceCostFact()
        {
            Id = -1;
        }

        public int Id { get; set; }
        public Guid UserRoleId { get; set; }
        public int StartPeriodId { get; set; }
        public int EndPeriodId { get; set; }
        public double CostPerHour { get; set; }
    }
}
