using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named SystemEventPropertyHistory.cs

namespace ESC2.Module.System.Data.DataObjects.Logging
{
    public partial class SystemEventPropertyHistory : IDataObject<long>
    {
        public SystemEventPropertyHistory()
        {
            Id = 0;
        }

        public long Id { get; set; }
        public long? SystemEventHistoryId { get; set; }
        public string ParameterName { get; set; }
        public string ParameterValue { get; set; }
    }
}
