using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named Asset.cs

namespace ESC2.Module.System.Data.DataObjects.Operational
{
    public partial class Asset : IDataObject<Guid>
    {
        public Asset()
        {
            Id = Guid.NewGuid();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string HostName { get; set; }
        public Guid? ContactEmployeeId { get; set; }
        public Guid? OwningDepartmentId { get; set; }
        public Guid? ParentAssetId { get; set; }
        public Guid AssetTypeId { get; set; }
        public Guid CreatedById { get; set; }
        public DateTime CreatedOn { get; set; }
        public Guid LastModifiedById { get; set; }
        public DateTime LastModifiedOn { get; set; }
    }
}
