using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named EvidenceSet.cs

namespace ESC2.Module.System.Data.DataObjects.Operational
{
    public partial class EvidenceSet : IDataObject<Guid>
    {
        public EvidenceSet()
        {
            Id = Guid.NewGuid();
        }

        public Guid Id { get; set; }
        public string Type { get; set; }
        public Guid CreatedById { get; set; }
        public DateTime CreatedOn { get; set; }
    }
}
