using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named AdjustmentSetRepo.cs
namespace ESC2.Module.System.Data.Repos
{
    public partial class AdjustmentSetRepo : AbstractGuidRepo<ESC2.Module.System.Data.DataObjects.AdjustmentSet>
    {
        public AdjustmentSetRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "dbo";
        public override string TableName => "adjustment_set";

        public override string InsertSql => @"
            INSERT INTO [dbo].[adjustment_set] (
                [dbo].[adjustment_set].[AdjustmentSetId],
                [dbo].[adjustment_set].[RuleId])
            VALUES ( 
                @Id,
                @RuleId) ";

        public override string UpdateSql => @"
            UPDATE [dbo].[adjustment_set] 
            SET [dbo].[adjustment_set].[rule_id]=@RuleId
            WHERE [dbo].[adjustment_set].[adjustment_set_id]=@Id ";

        public override string SelectSql => @"
            SELECT [dbo].[adjustment_set].[adjustment_set_id],
                   [dbo].[adjustment_set].[rule_id]
            FROM [dbo].[adjustment_set] ";

        public override ESC2.Module.System.Data.DataObjects.AdjustmentSet ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.AdjustmentSet();
            obj.Id = row.GetGuid("adjustment_set_id");
            obj.RuleId = row.GetGuid("rule_id");
            return obj;
        }


        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.AdjustmentSet obj)
         {
             List<DbQueryParameter> parameters = new List<DbQueryParameter>();
             parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
             parameters.Add(new DbQueryParameter("RuleId", obj.RuleId, DbQueryParameterType.Guid));

             return parameters;
         }


    }
}
