using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named AdjustmentRepo.cs
namespace ESC2.Module.System.Data.Repos
{
    public partial class AdjustmentRepo : AbstractGuidRepo<ESC2.Module.System.Data.DataObjects.Adjustment>
    {
        public AdjustmentRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "dbo";
        public override string TableName => "adjustment";

        public override string InsertSql => @"
            INSERT INTO [dbo].[adjustment] (
                [dbo].[adjustment].[AdjustmentId],
                [dbo].[adjustment].[Type],
                [dbo].[adjustment].[Details],
                [dbo].[adjustment].[AdjustmentSetId])
            VALUES ( 
                @Id,
                @Type,
                @Details,
                @AdjustmentSetId) ";

        public override string UpdateSql => @"
            UPDATE [dbo].[adjustment] 
            SET [dbo].[adjustment].[type]=@Type,
                [dbo].[adjustment].[details]=@Details,
                [dbo].[adjustment].[adjustment_set_id]=@AdjustmentSetId
            WHERE [dbo].[adjustment].[adjustment_id]=@Id ";

        public override string SelectSql => @"
            SELECT [dbo].[adjustment].[adjustment_id],
                   [dbo].[adjustment].[type],
                   [dbo].[adjustment].[details],
                   [dbo].[adjustment].[adjustment_set_id]
            FROM [dbo].[adjustment] ";

        public override ESC2.Module.System.Data.DataObjects.Adjustment ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.Adjustment();
            obj.Id = row.GetGuid("adjustment_id");
            obj.Type = row.GetString("type");
            obj.Details = row.GetString("details");
            obj.AdjustmentSetId = row.GetGuid("adjustment_set_id");
            return obj;
        }

        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.Adjustment obj)
        {
            List<DbQueryParameter> parameters = new List<DbQueryParameter>();
            parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("Type", obj.Type, DbQueryParameterType.String));
            parameters.Add(new DbQueryParameter("Details", obj.Details, DbQueryParameterType.String));
            parameters.Add(new DbQueryParameter("AdjustmentSetId", obj.AdjustmentSetId, DbQueryParameterType.Guid));

            return parameters;
        }
    }
}
