using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named AssetHistoryRepo.cs
namespace ESC2.Module.System.Data.Repos
{
    public partial class AssetHistoryRepo : AbstractGuidRepo<ESC2.Module.System.Data.DataObjects.AssetHistory>
    {
        public AssetHistoryRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "dbo";
        public override string TableName => "asset_history";

        public override string InsertSql => @"
            INSERT INTO [dbo].[asset_history] (
                [dbo].[asset_history].[AssetHistoryId],
                [dbo].[asset_history].[ActionDate],
                [dbo].[asset_history].[Action],
                [dbo].[asset_history].[UserId],
                [dbo].[asset_history].[AssetId])
            VALUES ( 
                @Id,
                @ActionDate,
                @Action,
                @UserId,
                @AssetId) ";

        public override string UpdateSql => @"
            UPDATE [dbo].[asset_history] 
            SET [dbo].[asset_history].[action_date]=@ActionDate,
                [dbo].[asset_history].[action]=@Action,
                [dbo].[asset_history].[user_id]=@UserId,
                [dbo].[asset_history].[asset_id]=@AssetId
            WHERE [dbo].[asset_history].[asset_history_id]=@Id ";

        public override string SelectSql => @"
            SELECT [dbo].[asset_history].[asset_history_id],
                   [dbo].[asset_history].[action_date],
                   [dbo].[asset_history].[action],
                   [dbo].[asset_history].[user_id],
                   [dbo].[asset_history].[asset_id]
            FROM [dbo].[asset_history] ";

        public override ESC2.Module.System.Data.DataObjects.AssetHistory ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.AssetHistory();
            obj.Id = row.GetGuid("asset_history_id");
            obj.ActionDate = row.GetDateTime("action_date");
            obj.Action = row.GetString("action");
            obj.UserId = row.GetGuid("user_id");
            obj.AssetId = row.GetGuid("asset_id");
            return obj;
        }


        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.AssetHistory obj)
         {
             List<DbQueryParameter> parameters = new List<DbQueryParameter>();
             parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
             parameters.Add(new DbQueryParameter("ActionDate", obj.ActionDate, DbQueryParameterType.DateTime));
             parameters.Add(new DbQueryParameter("Action", obj.Action, DbQueryParameterType.String));
             parameters.Add(new DbQueryParameter("UserId", obj.UserId, DbQueryParameterType.Guid));
             parameters.Add(new DbQueryParameter("AssetId", obj.AssetId, DbQueryParameterType.Guid));

             return parameters;
         }


    }
}
