using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named EvidenceSetRepo.cs
namespace ESC2.Module.System.Data.Repos
{
    public partial class EvidenceSetRepo : AbstractGuidRepo<ESC2.Module.System.Data.DataObjects.EvidenceSet>
    {
        public EvidenceSetRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "dbo";
        public override string TableName => "evidence_set";

        public override string InsertSql => @"
            INSERT INTO [dbo].[evidence_set] (
                [dbo].[evidence_set].[evidence_set_id],
                [dbo].[evidence_set].[type])
            VALUES ( 
                @Id,
                @Type) ";

        public override string UpdateSql => @"
            UPDATE [dbo].[evidence_set] 
            SET [dbo].[evidence_set].[type]=@Type
            WHERE [dbo].[evidence_set].[evidence_set_id]=@Id ";

        public override string SelectSql => @"
            SELECT [dbo].[evidence_set].[evidence_set_id],
                   [dbo].[evidence_set].[type]
            FROM [dbo].[evidence_set] ";

        public override ESC2.Module.System.Data.DataObjects.EvidenceSet ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.EvidenceSet();
            obj.Id = row.GetGuid("evidence_set_id");
            obj.Type = row.GetString("type");
            return obj;
        }

        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.EvidenceSet obj)
        {
            List<DbQueryParameter> parameters = new List<DbQueryParameter>();
            parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
            parameters.Add(new DbQueryParameter("Type", obj.Type, DbQueryParameterType.String));

            return parameters;
        }
    }
}
