using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named EvidenceRepo.cs
namespace ESC2.Module.System.Data.Repos
{
    public partial class EvidenceRepo : AbstractGuidRepo<ESC2.Module.System.Data.DataObjects.Evidence>
    {
        public EvidenceRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "dbo";
        public override string TableName => "evidence";

        public override string InsertSql => @"
            INSERT INTO [dbo].[evidence] (
                [dbo].[evidence].[EvidenceId],
                [dbo].[evidence].[DataLocation],
                [dbo].[evidence].[MimeType],
                [dbo].[evidence].[CreatedOn],
                [dbo].[evidence].[EvidenceSetId])
            VALUES ( 
                @Id,
                @DataLocation,
                @MimeType,
                @CreatedOn,
                @EvidenceSetId) ";

        public override string UpdateSql => @"
            UPDATE [dbo].[evidence] 
            SET [dbo].[evidence].[data_location]=@DataLocation,
                [dbo].[evidence].[mime_type]=@MimeType,
                [dbo].[evidence].[created_on]=@CreatedOn,
                [dbo].[evidence].[evidence_set_id]=@EvidenceSetId
            WHERE [dbo].[evidence].[evidence_id]=@Id ";

        public override string SelectSql => @"
            SELECT [dbo].[evidence].[evidence_id],
                   [dbo].[evidence].[data_location],
                   [dbo].[evidence].[mime_type],
                   [dbo].[evidence].[created_on],
                   [dbo].[evidence].[evidence_set_id]
            FROM [dbo].[evidence] ";

        public override ESC2.Module.System.Data.DataObjects.Evidence ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.Evidence();
            obj.Id = row.GetGuid("evidence_id");
            obj.DataLocation = row.GetString("data_location");
            obj.MimeType = row.GetString("mime_type");
            obj.CreatedOn = row.GetDateTime("created_on");
            obj.EvidenceSetId = row.GetGuid("evidence_set_id");
            return obj;
        }


        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.Evidence obj)
         {
             List<DbQueryParameter> parameters = new List<DbQueryParameter>();
             parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
             parameters.Add(new DbQueryParameter("DataLocation", obj.DataLocation, DbQueryParameterType.String));
             parameters.Add(new DbQueryParameter("MimeType", obj.MimeType, DbQueryParameterType.String));
             parameters.Add(new DbQueryParameter("CreatedOn", obj.CreatedOn, DbQueryParameterType.DateTime));
             parameters.Add(new DbQueryParameter("EvidenceSetId", obj.EvidenceSetId, DbQueryParameterType.Guid));

             return parameters;
         }


    }
}
