using System;
using System.Collections.Generic;
using System.Data;
using ESC2.Library.Data.Constants;
using ESC2.Library.Data.Repos;
using ESC2.Library.Data.Helpers;
using ESC2.Library.Data.Interfaces;
using ESC2.Library.Data.Objects;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named VersionRepo.cs
namespace ESC2.Module.System.Data.Repos
{
    public partial class VersionRepo : AbstractGuidRepo<ESC2.Module.System.Data.DataObjects.Version>
    {
        public VersionRepo(IDataProvider dataProvider)
             : base(dataProvider)
        {
        }

        public override string SchemaName => "dbo";
        public override string TableName => "version";

        public override string InsertSql => @"
            INSERT INTO [dbo].[version] (
                [dbo].[version].[VersionId],
                [dbo].[version].[Number],
                [dbo].[version].[Status],
                [dbo].[version].[StatusDate],
                [dbo].[version].[Title],
                [dbo].[version].[Description],
                [dbo].[version].[Publisher],
                [dbo].[version].[Source],
                [dbo].[version].[Filename],
                [dbo].[version].[ImplementationGuideId])
            VALUES ( 
                @Id,
                @Number,
                @Status,
                @StatusDate,
                @Title,
                @Description,
                @Publisher,
                @Source,
                @Filename,
                @ImplementationGuideId) ";

        public override string UpdateSql => @"
            UPDATE [dbo].[version] 
            SET [dbo].[version].[number]=@Number,
                [dbo].[version].[status]=@Status,
                [dbo].[version].[status_date]=@StatusDate,
                [dbo].[version].[title]=@Title,
                [dbo].[version].[description]=@Description,
                [dbo].[version].[publisher]=@Publisher,
                [dbo].[version].[source]=@Source,
                [dbo].[version].[filename]=@Filename,
                [dbo].[version].[implementation_guide_id]=@ImplementationGuideId
            WHERE [dbo].[version].[version_id]=@Id ";

        public override string SelectSql => @"
            SELECT [dbo].[version].[version_id],
                   [dbo].[version].[number],
                   [dbo].[version].[status],
                   [dbo].[version].[status_date],
                   [dbo].[version].[title],
                   [dbo].[version].[description],
                   [dbo].[version].[publisher],
                   [dbo].[version].[source],
                   [dbo].[version].[filename],
                   [dbo].[version].[implementation_guide_id]
            FROM [dbo].[version] ";

        public override ESC2.Module.System.Data.DataObjects.Version ToObject(DataRow row)
        {
            var obj = new ESC2.Module.System.Data.DataObjects.Version();
            obj.Id = row.GetGuid("version_id");
            obj.Number = row.GetString("number");
            obj.Status = row.GetString("status");
            obj.StatusDate = row.GetDateTime("status_date");
            obj.Title = row.GetString("title");
            obj.Description = row.GetString("description");
            obj.Publisher = row.GetString("publisher");
            obj.Source = row.GetString("source");
            obj.Filename = row.GetString("filename");
            obj.ImplementationGuideId = row.GetGuid("implementation_guide_id");
            return obj;
        }


        public override List<DbQueryParameter> ToParameters(ESC2.Module.System.Data.DataObjects.Version obj)
         {
             List<DbQueryParameter> parameters = new List<DbQueryParameter>();
             parameters.Add(new DbQueryParameter("Id", obj.Id, DbQueryParameterType.Guid));
             parameters.Add(new DbQueryParameter("Number", obj.Number, DbQueryParameterType.String));
             parameters.Add(new DbQueryParameter("Status", obj.Status, DbQueryParameterType.String));
             parameters.Add(new DbQueryParameter("StatusDate", obj.StatusDate, DbQueryParameterType.DateTime));
             parameters.Add(new DbQueryParameter("Title", obj.Title, DbQueryParameterType.String));
             parameters.Add(new DbQueryParameter("Description", obj.Description, DbQueryParameterType.String));
             parameters.Add(new DbQueryParameter("Publisher", obj.Publisher, DbQueryParameterType.String));
             parameters.Add(new DbQueryParameter("Source", obj.Source, DbQueryParameterType.String));
             parameters.Add(new DbQueryParameter("Filename", obj.Filename, DbQueryParameterType.String));
             parameters.Add(new DbQueryParameter("ImplementationGuideId", obj.ImplementationGuideId, DbQueryParameterType.Guid));

             return parameters;
         }


    }
}
