using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named Audit.cs

namespace ESC2.Module.System.Data.DataObjects
{
    public partial class Audit : IGuidObject
    {
        public Audit()
        {
            Id = Guid.NewGuid();
        }

        public Guid Id { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string Status { get; set; }
        public string Summary { get; set; }
        public Guid? EmployeeId { get; set; }
        public Guid? ImplementationId { get; set; }
    }
}
