using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named ImplementationGuide.cs

namespace ESC2.Module.System.Data.DataObjects
{
    public partial class ImplementationGuide : IGuidObject
    {
        public ImplementationGuide()
        {
            Id = Guid.NewGuid();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string Version { get; set; }
        public int NumberOfRules { get; set; }
    }
}
