using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named ImplementationFact.cs

namespace ESC2.Module.System.Data.DataObjects
{
    public partial class ImplementationFact : IGuidObject
    {
        public ImplementationFact()
        {
            Id = Guid.NewGuid();
        }

        public Guid Id { get; set; }
        public Guid ImplementationId { get; set; }
        public Guid AssetId { get; set; }
        public Guid ImplementationGuideId { get; set; }
        public Guid EmployeeId { get; set; }
        public long StartedOnPeriodId { get; set; }
        public long CompletedOnPeriodId { get; set; }
        public double HoursToComplete { get; set; }
    }
}
