using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named Period.cs

namespace ESC2.Module.System.Data.DataObjects
{
    public partial class Period : IIdentityObject<long>
    {
        public Period()
        {
            Id = 0;
        }

        public long Id { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Day { get; set; }
        public byte DayOfWeek { get; set; }
    }
}
