using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named ResourceCostFact.cs

namespace ESC2.Module.System.Data.DataObjects
{
    public partial class ResourceCostFact : IGuidObject
    {
        public ResourceCostFact()
        {
            Id = Guid.NewGuid();
        }

        public Guid Id { get; set; }
        public Guid RoleId { get; set; }
        public long StartPeriodId { get; set; }
        public long EndPeriodId { get; set; }
        public double CostPerHour { get; set; }
    }
}
