using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named SystemEvent.cs

namespace ESC2.Module.System.Data.DataObjects
{
    public partial class SystemEvent : IIdentityObject
    {
        public SystemEvent()
        {
        }

        public long Id { get; set; }
        public long? CustomerId { get; set; }
        public DateTime? ReceivedAt { get; set; }
        public DateTime? DeviceReportedTime { get; set; }
        public short? Facility { get; set; }
        public short? Priority { get; set; }
        public string FromHost { get; set; }
        public string Message { get; set; }
        public int? NtSeverity { get; set; }
        public int? Importance { get; set; }
        public string EventSource { get; set; }
        public string EventUser { get; set; }
        public int? EventCategory { get; set; }
        public int? EventId { get; set; }
        public string EventBinaryData { get; set; }
        public int? MaximumAvailable { get; set; }
        public int? CurrentUsage { get; set; }
        public int? MinimumUsage { get; set; }
        public int? MaximumUsage { get; set; }
        public int? InfoUnitId { get; set; }
        public string SysLogTag { get; set; }
        public string EventLogType { get; set; }
        public string GenericFileName { get; set; }
        public int? SystemId { get; set; }
    }
}
