using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named SystemEventSeverity.cs

namespace ESC2.Module.System.Data.DataObjects
{
    public partial class SystemEventSeverity : IIdentityObject<byte>
    {
        public SystemEventSeverity()
        {
            Id = 0;
        }

        public byte Id { get; set; }
        public string Name { get; set; }
    }
}
