using System;
using System.Collections.Generic;
using ESC2.Library.Data.Interfaces;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator
// To extend the class beyond a POCO, create a additional partial class
// named SystemEventProperty.cs

namespace ESC2.Module.System.Data.DataObjects
{
    public partial class SystemEventProperty : IIdentityObject
    {
        public SystemEventProperty()
        {
            Id = 0;
        }

        public long Id { get; set; }
        public long? SystemEventId { get; set; }
        public string ParameterName { get; set; }
        public string ParameterValue { get; set; }
    }
}
