using ESC2.Library.Data.Constants;

// This file is generated from the database.  Do not manually edit.
// Generated by: https://github.com/brian-nelson/repo-generator

namespace ESC2.Library.Data.Objects
{
    public class DbQueryParameter
    {
        public DbQueryParameter() {}

        public DbQueryParameter(string name, object value, DbQueryParameterType parameterType, int? size = null)
        {
            Name = name;
            Value = value;
            ParameterType = parameterType;
            Size = size;
        }

        public string Name { get; set; }
        public object Value { get; set; }
        public int? Size { get; set; }
        public DbQueryParameterType ParameterType { get; set; }
    }
}
