INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (0, 'Kernel messages');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (1, 'User-level messages');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (2, 'Mail System');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (3, 'System Daemons');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (4, 'Securty/Authorization Messages');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (5, 'Messages generated by syslogd');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (6, 'Line Printer Subsystem');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (7, 'Network News Subsystem');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (8, 'UUCP Subsystem');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (9, 'Clock Daemon');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (10, 'Security/Authorization Messages');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (11, 'FTP Daemon');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (12, 'NTP Subsystem');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (13, 'Log Audit');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (14, 'Log Alert');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (15, 'Clock Daemon');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (16, 'Local Use 0');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (17, 'Local Use 1');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (18, 'Local Use 2');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (19, 'Local Use 3');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (20, 'Local Use 4');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (21, 'Local Use 5');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (22, 'Local Use 6');

INSERT INTO dbo.system_event_facility (system_event_facility_id, name)
VALUES (23, 'Local Use 7');

INSERT INTO dbo.system_event_severity (system_event_severity_id, name)
VALUES (0, 'Emergency');

INSERT INTO dbo.system_event_severity (system_event_severity_id, name)
VALUES (1, 'Alert');

INSERT INTO dbo.system_event_severity (system_event_severity_id, name)
VALUES (2, 'Critical');

INSERT INTO dbo.system_event_severity (system_event_severity_id, name)
VALUES (3, 'Error');

INSERT INTO dbo.system_event_severity (system_event_severity_id, name)
VALUES (4, 'Warning');

INSERT INTO dbo.system_event_severity (system_event_severity_id, name)
VALUES (5, 'Notice');

INSERT INTO dbo.system_event_severity (system_event_severity_id, name)
VALUES (6, 'Informational');

INSERT INTO dbo.system_event_severity (system_event_severity_id, name)
VALUES (7, 'Debug');